# Generated by Django 4.0.2 on 2022-02-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tag',
            field=models.CharField(blank=True, choices=[('h', 'hot!'), ('p', 'popular'), ('s', 'special'), ('n', 'seasonal')], max_length=1, null=True),
        ),
    ]
