# Generated by Django 4.0.2 on 2022-02-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_alter_dish_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tag',
            field=models.CharField(blank=True, choices=[('hot!', 'hot!'), ('popular', 'popular'), ('special', 'special'), ('seasonal', 'seasonal')], max_length=15, null=True),
        ),
    ]
